name: "Setup Java + Gradle (with cache)"
description: "Sets up Java and Gradle, and enables Gradle wrapper/caches via actions/cache."

inputs:
  java-version:
    description: "Java version to use"
    required: false
    default: '21'
  distribution:
    description: "JDK distribution"
    required: false
    default: temurin

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
