name: Level 1 - Yoshi's Island

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Compile
        uses: ./.github/actions/setup-java-gradle

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test
